# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [2]:
import numpy as np
Z = np.zeros(100)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
Z = np.ones(100)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
Z = np.full(100, 3)
print(Z)

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Поменять 2 строки в матрице

In [5]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 5. Создать вектор со значениями от 10 до 100

In [6]:
Z = np.arange(10,100)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [7]:
A = np.arange(16).reshape(4,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [8]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [9]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.73320961 0.23707654 0.48502407]
  [0.48749453 0.11140063 0.06377298]
  [0.42547072 0.67560416 0.9435639 ]]

 [[0.37045338 0.21900974 0.77837679]
  [0.30030418 0.89841454 0.79292138]
  [0.2269943  0.59074311 0.45089955]]

 [[0.54981348 0.83614052 0.06533181]
  [0.87559221 0.30407939 0.08099246]
  [0.02398275 0.33961582 0.25858267]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [11]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.93598769 0.88242668 0.78265765 0.5895573  0.15939403 0.09979547
  0.84733068 0.57018318 0.61985153 0.45405772]
 [0.89927214 0.22233305 0.60754369 0.47400172 0.51145271 0.81463889
  0.48798426 0.44680947 0.05337306 0.127218  ]
 [0.87892432 0.83179024 0.57326595 0.75922649 0.39032944 0.63571589
  0.99530034 0.12297692 0.76652278 0.01341658]
 [0.07152075 0.87395562 0.73096032 0.15368165 0.99954571 0.80662095
  0.68800069 0.19599637 0.82579987 0.95724303]
 [0.86078453 0.64216149 0.18734616 0.31792576 0.39007656 0.98349217
  0.92774913 0.59913221 0.70526643 0.13612859]
 [0.09093009 0.89190151 0.09711576 0.13829324 0.13443454 0.11480093
  0.56771196 0.84062966 0.92085871 0.14097037]
 [0.29560583 0.66118956 0.74350811 0.02024169 0.59168772 0.34638666
  0.63305976 0.15104196 0.40721486 0.604615  ]
 [0.18430825 0.12575284 0.0497976  0.43186414 0.34929301 0.83644349
  0.41184802 0.33888863 0.92977601 0.31109851]
 [0.20909712 0.08170531 0.6722058  0.7439797  0.67682653 0.35501716
  0.44028331

#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [12]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.51948535734626


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [13]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [14]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [17]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [18]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [20]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

[[9.26710220e-01 5.98615332e-01 1.95232426e-02 2.68886246e-04
  3.44081874e-01 1.02722548e-01 9.90840891e-01 6.49089000e-01
  7.54196342e-01 4.89984514e-01]
 [7.56727037e-02 6.93092181e-01 6.09688612e-01 1.83744622e-01
  4.37958544e-01 4.73984612e-01 9.17329065e-01 9.10788025e-01
  6.53578946e-01 3.69063418e-02]
 [2.65212094e-01 1.52424992e-01 5.07950735e-03 3.56061141e-01
  8.54240089e-01 9.43896642e-01 3.44783035e-02 4.33002468e-01
  5.52893767e-02 1.72588789e-01]
 [7.11436454e-01 9.35318465e-02 1.21015290e-01 6.83605967e-03
  1.83434841e-01 2.77288544e-01 6.34619786e-01 9.68525987e-01
  3.56985993e-01 9.74964283e-01]
 [9.34096941e-01 6.41834594e-02 4.49241632e-01 9.01733634e-01
  2.15571066e-01 2.30019175e-01 3.21863457e-01 5.90456987e-01
  3.85901174e-01 4.51158274e-01]]
[[ 0.43910694  0.11101205 -0.46808004 -0.4873344  -0.14352141 -0.38488074
   0.50323761  0.16148571  0.26659306  0.00238123]
 [-0.42360166  0.19381782  0.11041425 -0.31552974 -0.06131582 -0.02528975
   0.4180547   